requires "Kossy", 0.38;
requires "DBIx::Sunny";

requires "JSON::XS";
requires "DBD::Pg";
requires "Starman";
requires "Plack::Session";
requires "Furl";
requires "IO::Socket::SSL";
requires "String::Util";
