requires "Kossy", 0.38;
requires "DBIx::Sunny";

requires "DBD::Pg";
requires "Starman";
requires "Plack::Session";
requires "Furl";
requires "IO::Socket::SSL";
requires "String::Util";

requires "Gazelle";
requires "Server::Starter";
requires 'Cache::Memcached::Fast';

requires 'AnyEvent';
requires 'AnyEvent::HTTP';
requires 'EV';
